In [13]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define the network structure
class TestMasking(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        # Define the layers and operations
        super().__init__()
        self.fc1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)  

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

# Hyperparameters
input_size = 4 
hidden_size = 10
num_classes = 5
learning_rate = 0.001

# Initialize the network
model = TestMasking(input_size, hidden_size, num_classes)

# Loss and optimizer
loss_fn = nn.CrossEntropyLoss()  # Suitable for classification tasks
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Now you can proceed to train the model with your dataset.

num_samples = 3
inputs = torch.randn(num_samples, input_size)
targets = torch.randint(0, num_classes, (num_samples,))

In [14]:
import pdb

def train():
    model.train()
    epochs = 2

    for i in range(epochs):
        for j in range(num_samples):
            pdb.set_trace()
            
            logits = model(inputs[j])
            mask = torch.tensor([1.,1.,1.,0.,0.])
            masked_logits = logits * mask
            optimizer.zero_grad()
            loss = loss_fn(masked_logits, targets[j])
            loss.backward()
            optimizer.step()

In [15]:
train()

> /tmp/ipykernel_12708/262845173.py(11)train()
      9             pdb.set_trace()
     10 
---> 11             logits = model(inputs[j])
     12             mask = torch.tensor([1.,1.,1.,0.,0.])
     13             masked_logits = logits * mask



ipdb>  n


> /tmp/ipykernel_12708/262845173.py(12)train()
     10 
     11             logits = model(inputs[j])
---> 12             mask = torch.tensor([1.,1.,1.,0.,0.])
     13             masked_logits = logits * mask
     14             optimizer.zero_grad()



ipdb>  n


> /tmp/ipykernel_12708/262845173.py(13)train()
     11             logits = model(inputs[j])
     12             mask = torch.tensor([1.,1.,1.,0.,0.])
---> 13             masked_logits = logits * mask
     14             optimizer.zero_grad()
     15             loss = loss_fn(masked_logits, targets[j])



ipdb>  n


> /tmp/ipykernel_12708/262845173.py(14)train()
     12             mask = torch.tensor([1.,1.,1.,0.,0.])
     13             masked_logits = logits * mask
---> 14             optimizer.zero_grad()
     15             loss = loss_fn(masked_logits, targets[j])
     16             loss.backward()



ipdb>  n


> /tmp/ipykernel_12708/262845173.py(15)train()
     13             masked_logits = logits * mask
     14             optimizer.zero_grad()
---> 15             loss = loss_fn(masked_logits, targets[j])
     16             loss.backward()
     17             optimizer.step()



ipdb>  loss


CrossEntropyLoss()


ipdb>  n


> /tmp/ipykernel_12708/262845173.py(16)train()
     13             masked_logits = logits * mask
     14             optimizer.zero_grad()
     15             loss = loss_fn(masked_logits, targets[j])
---> 16             loss.backward()
     17             optimizer.step()



ipdb>  loss


tensor(1.2120, grad_fn=<NllLossBackward0>)


ipdb>  loss_fn(logits, targets[j])


tensor(1.1622, grad_fn=<NllLossBackward0>)


ipdb>  n


> /tmp/ipykernel_12708/262845173.py(17)train()
     13             masked_logits = logits * mask
     14             optimizer.zero_grad()
     15             loss = loss_fn(masked_logits, targets[j])
     16             loss.backward()
---> 17             optimizer.step()



ipdb>  quit


In [ ]:
def test_mask():
    fc1 = nn.Linear(input_size, hidden_size, requires_grad=True)
    relu = nn.ReLU(requires_grad=True)
    fc2 = nn.Linear(hidden_size, num_classes, requires_grad=True)
    
    logits = inputs[0]
    logits = fc1(logits)
    logits = relu(logits)
    logits = fc2(logits)

    mask = torch.tensor([1.,1.,1.,0.,0])
    masked_logits = logits * mask

    loss_fn = nn.CrossEntropyLoss()
    loss = loss_fn(inputs[0], targets[0])
    loss.backward()
    
    



torch.Size([452, 97])

In [3]:
mask

tensor([[1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        ...,
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.]])

In [7]:
logits = torch.randn(size=(2,5))
logits

tensor([[-2.1145, -0.7501, -0.3871,  1.3972,  1.0370],
        [-0.0719, -0.1498,  1.0124, -0.2974,  0.0954]])

In [15]:
mask = torch.zeros(size=(logits.shape[0],5))
mask[:, :3] = 1.0
mask

tensor([[1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]])

In [16]:
logits * mask

tensor([[-2.1145, -0.7501, -0.3871,  0.0000,  0.0000],
        [-0.0719, -0.1498,  1.0124, -0.0000,  0.0000]])